// MODULE: lib
// ENABLE_HILT_KSP
// WITH_DAGGER
// DISABLE_METRO
// FILE: MyHiltModule.kt
// Lib runs Hilt's real `KspAggregatedDepsProcessor` so the `hilt_aggregated_deps/...` marker is
// generated by Hilt itself rather than hand-written. This validates that Metro's interop reads
// the real-world canonical-name format (`JavaPoet.ClassName.canonicalName()` strings) correctly.
package test

import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
class MyHiltModule {
  @Provides fun provideMessage(): String = "Hello from Hilt KSP"
}

// MODULE: main(lib)
// ENABLE_HILT_INTEROP
// ENABLE_DAGGER_INTEROP

import javax.inject.Singleton

@DependencyGraph(Singleton::class)
interface AppGraph {
  val message: String
}

fun box(): String {
  val graph = createGraph<AppGraph>()
  assertEquals("Hello from Hilt KSP", graph.message)
  return "OK"
}
