name: Bug Report
description: Create a bug report
labels: [ "bug" ]
assignees: [ ]
body:
  - type: markdown
    attributes:
      value: |
        Please follow the instructions below.

        If you have a usage or debugging question, please use the [Q&A feature of the repo's Discussions section](https://github.com/ZacSweers/metro/discussions/new?category=q-a) instead of creating an issue.

        Provide a brief summary of the issue in the title above
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the high level issue (what crashed, what behavior you encountered, etc).
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Self-contained Reproducer
      description: |
        Provide a [minimal, self-contained example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) example that reproduces the issue.
        Ideally, fork this repo and create a test case in integration or compiler unit tests that reproduces this and then link that here.
        A link to a minimally reproducible project is also good.
        If you cannot supply a repro case, it may be difficult or impossible to help. In this event, be as detailed as you can.
        
        When submitting, include any relevant stack traces as you can and use conventional markdown formatting for readability.
    validations:
      required: true
  - type: input
    id: metro-version
    attributes:
      label: Metro version
      description: What version of Metro are you using?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Include as many relevant details about the environment as you can. Which platform, is it a compiler or runtime bug, etc.
    validations:
      required: false