#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }

REMOTE=$1

# Disable lock verification for non-origin remotes
if [ "$REMOTE" != "origin" ]; then
    git config lfs.locksverify false
else
    git config lfs.locksverify true
fi

git lfs pre-push "$@"
