# Copyright (C) 2026 Zac Sweers
# SPDX-License-Identifier: Apache-2.0

plugin.id=dev.zacsweers.metro.compiler
supported.kotlin.compiler.version=2.5.0-dev-3513
supported.kotlin.git.tag=build-2.5.0-dev-3513
supported.kotlin.git.commit=7e190e23816932c1f2de2fa400ee203131cf0c47
expected.output=OK
