// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.trace.internal

import dev.zacsweers.metro.Provider

/**
 * Provider decorator used by Metro-generated code when runtime tracing is enabled.
 *
 * Each invocation opens a trace section whose visible name is derived from [qualifier] and
 * [binding], delegates to [provider], and closes the section even if the delegate throws.
 *
 * @param traceContext graph-local tracing state generated by Metro.
 * @param qualifier rendered binding qualifier, or `null` when the binding is unqualified.
 * @param binding rendered binding type without its qualifier.
 * @param kind rendered binding implementation kind, or `null` when codegen has not supplied one.
 * @param provider Metro provider that creates or returns the binding value.
 */
public class TracedProvider<T>(
  private val traceContext: MetroTraceContext,
  private val qualifier: String?,
  private val binding: String,
  private val kind: String?,
  private val provider: Provider<T>,
) : Provider<T> {
  override fun invoke(): T {
    val traceName =
      if (qualifier == null) {
        binding
      } else {
        "$qualifier $binding"
      }

    return traceContext.trace(
      name = traceName,
      qualifier = qualifier,
      binding = binding,
      kind = kind,
    ) {
      provider.invoke()
    }
  }
}
