// Copyright (C) 2026 Zac Sweers
// SPDX-License-Identifier: Apache-2.0
package dev.zacsweers.metro.compiler.hilt

import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import dev.zacsweers.metro.compiler.memoize
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.types.constructClassLikeType
import org.jetbrains.kotlin.name.ClassId

/**
 * Surfaces Hilt `@InstallIn @EntryPoint` interfaces as graph supertypes for FIR-merged graphs.
 * Covers in-round source classes (predicate scan) and compiled classpath `@AggregatedDeps` markers
 * from Hilt's own KSP/KAPT processor.
 *
 * Cross-module Metro-only discovery (no `@AggregatedDeps` marker, just `includeHilt()` upstream)
 * goes through the nested `@MetroContribution`-annotated interface that
 * [HiltFirDeclarationExtension] generates on each entry point plus its emitted hint - same shape
 * Metro uses for `@ContributesTo`.
 */
public class HiltContributionExtension(
  private val session: FirSession,
  compatContext: CompatContext,
) : MetroContributionExtension, CompatContext by compatContext {

  private val scanner by memoize { HiltAggregatedDepsScanner(session) }

  /** Owns this extension's single-pass in-round `@InstallIn` scan. */
  private val componentScopes by memoize { HiltComponentScopeMapping(session) }

  override fun FirDeclarationPredicateRegistrar.registerPredicates() {
    // The `@InstallIn` predicate is registered by [HiltFirDeclarationExtension]; predicates are
    // session-global so we can query it here without re-registering.
  }

  override fun getContributions(
    scopeClassId: ClassId,
    typeResolverFactory: MetroFirTypeResolver.Factory,
  ): List<MetroContributionExtension.Contribution> {
    val contributions = mutableListOf<MetroContributionExtension.Contribution>()

    // Classpath `@AggregatedDeps` entry points (Hilt's processor writes these; Metro doesn't).
    for (dep in scanner.deps()) {
      if (dep.entryPoints.isEmpty()) continue
      if (dep.components.none { componentScopes.resolveScope(it) == scopeClassId }) continue
      for (entryPointClassId in dep.entryPoints) {
        contributions += contributionFor(entryPointClassId)
      }
    }

    // In-round source `@InstallIn @EntryPoint` interfaces. The nested `@MetroContribution`
    // interface generated by [HiltFirDeclarationExtension] handles the cross-module path; this
    // path covers same-compilation graphs regardless of which hint-emission mode is active.
    for (installIn in componentScopes.inRoundInstallIns) {
      if (!installIn.isEntryPoint) continue
      if (scopeClassId !in installIn.resolvedScopes(componentScopes)) continue
      contributions += contributionFor(installIn.classId)
    }

    return contributions
  }

  private fun contributionFor(entryPointClassId: ClassId): MetroContributionExtension.Contribution =
    MetroContributionExtension.Contribution(
      supertype = entryPointClassId.constructClassLikeType(emptyArray()),
      replaces = emptyList(),
      originClassId = entryPointClassId,
    )

  public class Factory : MetroContributionExtension.Factory {
    override fun create(
      session: FirSession,
      options: MetroOptions,
      compatContext: CompatContext,
    ): MetroContributionExtension? {
      if (!options.enableHiltInterop) return null
      return HiltContributionExtension(session, compatContext)
    }
  }
}
