name: CI

on:
  # Only run push on main
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  # Always run on PRs
  pull_request:
    branches: [ main ]

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    name: "platform / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      # windows-latest and macos-latest are excluded from these tests because frankly they are expensive $$ to run on CI
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          # Only save Gradle User Home state for builds on the 'main' branch.
          # Builds on other branches will only read existing entries from the cache.
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

          # Don't reuse cache entries from any other Job.
          gradle-home-cache-strict-match: true

          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Cache konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/cache
            ~/.konan/dependencies
            ~/.konan/kotlin-native-macos*
            ~/.konan/kotlin-native-mingw*
            ~/.konan/kotlin-native-windows*
            ~/.konan/kotlin-native-linux*
            ~/.konan/kotlin-native-prebuilt-macos*
            ~/.konan/kotlin-native-prebuilt-mingw*
            ~/.konan/kotlin-native-prebuilt-windows*
            ~/.konan/kotlin-native-prebuilt-linux*
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Test
        run: ./gradlew check --quiet

#  publish:
#    runs-on: macos-14
#    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && github.repository == 'zacsweers/lattice'
#    needs: [ build ]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
#
#      - name: Configure JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '23'
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          # Only save Gradle User Home state for builds on the 'main' branch.
#          # Builds on other branches will only read existing entries from the cache.
#          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
#
#          # Don't reuse cache entries from any other Job.
#          gradle-home-cache-strict-match: true
#
#          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
#
#      - name: Upload snapshot (main only)
#        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SonatypeUsername }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SonatypePassword }}
#        run: ./publish.sh
